  default: &default
    adapter: postgresql
    encoding: unicode
    username:  postgres 
    password: Welcome@*963.
    host: localhost

  development:
    <<: *default
    database: assignment_development

  test:
    <<: *default
    database: assignment_test

  production:
    <<: *default
    database: assignment_production
    username:  postgres 
    password: Welcome@*963.